[tool.poetry]
name = "cdap_geo_utils"
version = "0.1.0"
description = "An attempt at using Shapely and Geopandas with Spark."
authors = ["Andrew West <andrew.west@defra.gov.uk>"]

[tool.poetry.dependencies]
python = ">=3.7"
GDAL = ">=3"
pyspark = ">=3"
shapely
geopandas = ">=0.8"
