name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install GDAL 3.3.2
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y libgdal-dev=3.3.2+dfsg-2~focal2
      - name: Install nox
        run: python -m pip install nox==2021.6.12
      - name: Install poetry
        run: python -m pip install poetry==1.1.4
  check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run nox
        run: nox
        # env:
        #   CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
